Sprint 1/step 2
danielginz/react-burger pull request #1
Opened 2023-02-17 13:26 UTC by danielginz

Sprint 1, step 2, Daniel G

2023-02-17 20:02 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Данные получают с сервера;

### **Но есть несколько замечаний, которые нужно исправить:**

- Вам нужно исправить ошибку в консоли <https://disk.yandex.com/i/NECEfYdOvrDW1w>;

- У вас не запускается приложение на версии ноды `v19.4.0`, обновите пакет `react-scripts`;

- Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  ```

  Проверьте во всём проекте;

- Не открывается модальное окно, по клику на ингредиент <https://disk.yandex.com/i/AaIPWHn2mokGSA>;

- <https://disk.yandex.com/i/dgc5FmIV1YTwVA> - По макету, тут должен быть стилизованный скролл;

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-02-17 20:02 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +const API_URL = 'https://norma.nomoreparties.space/api/ingredients';
**Надо исправить:**
вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

2023-02-17 20:02 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +        hasLoaded: false,
**Можно лучше:** 

Не думаю, что поле isLoaded необходимо, вместо него можно воспользоваться проверкой на пустоту массива. `items.length`;

2023-02-17 20:02 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +    const [orderId, setOrderId] = useState('034536');
**Надо исправить:**

Тут лучше использовать обычную переменную, а также, не забывайте, что константы принято писать в стиле UPPER_CASE))

А ещё перенесите эту переменную в компонент `orderDetails`.

2023-02-17 20:02 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +    const [selectedItem, setSelectedItem] = useState([]);
**Надо исправить:**

Тут должен храниться 1 объект, а не массив. 

Также если нет значения, то нужно использовать null, а не пустой объект.

2023-02-17 20:02 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +            return fetch(API_URL)
**Можно лучше:**

Тут не нужен return.

**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```js
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-02-17 20:02 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +    };
**Надо исправить:**

Для каждого модального окна, должен быть свой обработчик закрытия.

2023-02-17 20:02 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +    const middleItems = ingredientsData.items.filter(item => (item.type === 'sauce' || item.type === 'main')).slice(4, 12);
**Надо исправить:**

Эти переменные лучше объявить в компоненте `burger-constructor`.

**Можно лучше:**

Лучше написать так: 

```js
const bun = ingredientsData.items.find(item => item.type === 'bun');
const ingredients = ingredientsData.items.filter(item => item.type !== 'bun'.slice(4, 12);
```

2023-02-17 20:02 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +                )}
**Можно лучше:**

Здесь и далее, кажется вы тут намудрили немного можно проще. 

Просто если `ingredientsData.hasError` то рендерите ошибку, если `ingredientsData.isLoading`, то лоадер и т.д.

2023-02-17 20:02 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +                )}
**Можно лучше:**

Лучше рендерить попапы в компонентах к которым они относятся - `burger-ingredients` и `burger-constructor`.

2023-02-17 20:02 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +};
**Надо исправить:**

в propTypes вам требуется указать полное описание ингредиента, а у вас не хватает полей.

2023-02-17 20:02 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +                        props.middleItems.reduce((acc, p) => acc + p.price, 0)
**Надо исправить:**

Лучше вынести в useMemo.

2023-02-17 20:02 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +                <li className='pl-8' key="top_bun">
**Надо исправить:**

Вам тут не нужно указывать key. 

Советую ещё раз прочитать документацию. 
https://ru.react.js.org/docs/lists-and-keys.html

2023-02-17 20:02 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    items: PropTypes.arrayOf(PropTypes.shape({type: PropTypes.string.isRequired}).isRequired).isRequired
**Надо исправить:**

Нужно полное описание ингрединта, там намного больше полей)

2023-02-17 20:02 UTC, ArslanMustafin commented on src/components/burger-ingredients-category/burger-ingredients-category.jsx
> +    }).isRequired).isRequired
**Надо исправить:**

Требуется полное описание структуры ингредиента.

2023-02-17 20:02 UTC, ArslanMustafin commented on src/components/ingredient-details/ingredient-details.jsx
> +    }).isRequired
**Надо исправить:**

Требуется полное описание структуры ингредиента

2023-02-17 20:02 UTC, ArslanDev666 commented on src/components/order-details/order-details.jsx
> +    ]).isRequired
**Надо исправить:**

мне кажется, тут должно быть что-то одно, тем более на данном этапе, вы полностью контролируете это значение.

2023-02-19 09:16 UTC, danielginz commented on src/components/burger-ingredients-card/burger-ingredients-card.jsx
> +};
Добрый день, насколько я вижу тут нет props.item, пока я его не добавил.
Спасибо
![image](https://user-images.githubusercontent.com/42783698/219939463-adf9c167-f3f1-4869-a42d-1353aa7505c8.png)

2023-02-19 16:01 UTC, danielginz commented
Добрый день,
Я исправил все комменты "Надо исправить" и один коммент "Можно лучше".
Кроме того я увидел, что у меня не работало корректно "openIngredientModal" в классе App, т.к. объект clickedItem был пустой и не имел значение. Я это исправил, поэтому теперь в OrderDetails передаётся корректный item, но когда вызывается Модал, то вылетает ошибка "Target container is not a DOM element."
Я на этом застрял и голова уже не работает, потому посылаю в таком виде.
Спасибо

2023-02-19 17:44 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Но есть несколько замечаний, которые нужно исправить:**

- Вам нужно исправить ошибки в консоли <https://disk.yandex.com/i/L1_iPJF_uYpZjw>;

- Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  ```

  Проверьте во всём проекте;

- Не открывается модальное окно, по клику на ингредиент;

- Не исправлены следующие замечания:
  - <https://github.com/danielginz/react-burger/pull/1#discussion_r1110279489>;
  - <https://github.com/danielginz/react-burger/pull/1#discussion_r1110287220>;
  - <https://github.com/danielginz/react-burger/pull/1#discussion_r1110287974>;

### **Ответ на комментарий:**

- Вы забыли написать `<div id="modal-root"></div>` в `public/index.html`, <https://disk.yandex.com/i/Lyp45wKQOIuuLw>;

2023-02-19 17:44 UTC, ArslanDev666 commented on src/components/order-details/order-details.jsx
> +    console.log("AAA, order-details, props: "+JSON.stringify(this.props));
**Надо исправить:**

В приложении не должно быть консоль логов, или дебаггеров.

2023-02-19 17:44 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    }).isRequired).isRequired
**Надо исправить:**

во многих компонентах дублируется описание PropTypes ингредиента.
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать

2023-02-19 17:44 UTC, ArslanDev666 commented on src/components/order-details/order-details.jsx
> +};
**Надо исправить:**

Не совсем понимаю, зачем тут ингредиент.

2023-02-20 13:01 UTC, danielginz commented
Добрый день,
Спасибо за ревью, я прошёл все замечания, надеюсь ничего не пропустил )

Только одно замечание я не смог исправить.

 **Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.
Пример как правильно:
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;**

Я не совсем понимаю как это можно сделать. Например есть следующая структура:
_ingredients: PropTypes.arrayOf(PropTypes.shape({
        name: PropTypes.string.isRequired,
        price: PropTypes.number.isRequired,
        image: PropTypes.string.isRequired,
        _id: PropTypes.string.isRequired
    })),_
Как её обернуть в эту проверку?
С тем же именем не получается сделать строчку.
_ingredientTypes: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;_

Тогда нужно создать новую переменную?
Спасибо

2023-02-20 15:49 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

- Практически все замечания были исправлены;

### **Но всё ещё есть несколько замечаний, которые нужно исправить:**

- В приложении не должно быть логов, или дебаггеров. Пройдитесь поиском и уберите пожалуйста. <https://disk.yandex.com/i/xbNKLDUAuvbV9Q>;

- Нужно исправить следующие замечание <https://github.com/danielginz/react-burger/pull/1#discussion_r1111290280>;

2023-02-20 15:49 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +    const calculatePrice = useMemo(() => calcPrice(), []);
**Можно лучше:**

Лучше написать вот так: 

```js
const totalPrice = useMemo(() => {
  return bun.price * 2 + ingredients.reduce((acc, p) => acc + p.price, 0);
}, [ingredients, bun]);
```
`useMemo` - должен возвращать значение)) поэтому лучше сразу делать вычисления, а не выносить в функцию))

2023-02-20 15:49 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +};
**Надо исправить:**

У вас описаны неправильные пропсы.

сейчас вы передаёте в компонент `burger-constructor` пропсы - `items` и `onOrderButtonClick`.

```js
// пропсы для items - это массив ингредиентов, а значит пропс будет следующим:
items: PropTypes.arrayOf(ingredientType.isRequired).isRequired;

// для 1 ингредиента (это просто пример, чтобы вы знали, как сделать пропс для 1 ингредиента)
item: ingredientType.isRequired;
```




Файл `utils/prop-types.js`, вам нужно его создать.
```js
export const ingredientType = PropTypes.shape({
    __v: PropTypes.number.isRequired,
    _id: PropTypes.string.isRequired,
    type: PropTypes.string.isRequired,
    name: PropTypes.string.isRequired,
    image: PropTypes.string.isRequired,
    image_mobile: PropTypes.string.isRequired,
    image_large: PropTypes.string.isRequired,
    calories: PropTypes.number.isRequired,
    proteins: PropTypes.number.isRequired,
    fat: PropTypes.number.isRequired,
    carbohydrates: PropTypes.number.isRequired,
    price: PropTypes.number.isRequired,
})
```

2023-02-20 15:57 UTC, ArslanDev666 commented
> Добрый день, Спасибо за ревью, я прошёл все замечания, надеюсь ничего не пропустил )
> 
> Только одно замечание я не смог исправить.
> 
> **Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes. Пример как правильно: data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;**
> 
> Я не совсем понимаю как это можно сделать. Например есть следующая структура: _ingredients: PropTypes.arrayOf(PropTypes.shape({ name: PropTypes.string.isRequired, price: PropTypes.number.isRequired, image: PropTypes.string.isRequired, _id: PropTypes.string.isRequired })),_ Как её обернуть в эту проверку? С тем же именем не получается сделать строчку. _ingredientTypes: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;_
> 
> Тогда нужно создать новую переменную? Спасибо

Здравствуйте, надеюсь, я правильно понял ваш вопрос, описал объяснение в комментарии https://github.com/danielginz/react-burger/pull/1#discussion_r1112110091.

1. У вас тут не хватало полей (вы ведь массив ингредиентов имели ввиду). Поэтому, для того чтобы структура была правильной и её можно было бы переиспользовать, я просил вынести полную структуру в отдельный файл.
 
2. А использовать `.isRequired`, можнло следующим образом:

```js
_ingredients: PropTypes.arrayOf(PropTypes.shape({
  name: PropTypes.string.isRequired,
  price: PropTypes.number.isRequired,
  image: PropTypes.string.isRequired,
  id: PropTypes.string.isRequired
}).isRequired).isRequired
```
Но, как я сказал ранее, эта структура не совсем полная))

3. Насчёт имени не понял вопроса.

2023-02-20 21:01 UTC, danielginz commented
Спасибо за объяснения

2023-02-21 05:56 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодец: Работа принята, удачи в дальнейшем обучении!**

- Практически все замечания были исправлены;

### **Нужно исправить (т.к. вы эти моменты уже знаете, работа будет зачтена):**

- Нужно исправить следующие замечание <https://github.com/danielginz/react-burger/pull/1#discussion_r1112110091>, написал в комментариях к коду, какие должны быть;

- Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes;

- Не забудьте, про замечания в коде;

2023-02-21 05:56 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    items: PropTypes.arrayOf(ingredientType).isRequired
**Надо исправить:**

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
    items: PropTypes.arrayOf(ingredientType.isRequired).isRequired
```

2023-02-21 05:56 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +BurgerIngredients.propTypes = {
**Надо исправить:** 

Описаны не все пропсы.

Не хватает описания для пропса `onIngredientClick`. 

Оно будет следующим: 
`onIngredientClick: PropTypes.func.isRequired`

2023-02-21 05:56 UTC, ArslanDev666 commented on src/components/ingredient-details/ingredient-details.jsx
> +function IngredientDetails(props) {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-02-21 05:56 UTC, ArslanDev666 commented on src/components/burger-ingredients-category/burger-ingredients-category.jsx
> +    items: PropTypes.arrayOf(ingredientType).isRequired
**Надо исправить:**

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

как правильно:

```js
items: PropTypes.arrayOf(ingredientType.isRequired).isRequired;
```

2023-02-21 05:56 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +};
Тут будут следующие пропсы: 

```js
items: PropTypes.arrayOf(ingredientType.isRequired).isRequired,
onOrderButtonClick: PropTypes.func.isRequired,
```

2023-02-21 11:32 UTC, merged