Sprint 3/step 1
danielginz/react-burger pull request #4
Opened 2023-03-15 11:29 UTC by danielginz

Sprint 3/step 1

2023-03-15 12:02 UTC, andryxxa93 requested changes
Здравствуйте! 
- Проект не собирается из-за ошибок, проверить функционал проекта не представляется возможным. Пожалуйста исправьте ошибки и пришлите работу снова на проверку.

<img width="1440" alt="Снимок экрана 2023-03-15 в 14 55 16" src="https://user-images.githubusercontent.com/60173362/225301876-b37d3b91-8971-49fa-989b-a206efac3795.png">

2023-03-15 12:02 UTC, andryxxa93 commented on src/app.jsx
> +    state => state.items
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-03-15 12:02 UTC, andryxxa93 commented on src/app.jsx
> +        <Route path="/feed" element={<FeedPage />} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-03-15 13:04 UTC, danielginz commented
Здравствуйте, а в каком модулепроект падает? Или сразу падает?
У меня поднимается.
![image](https://user-images.githubusercontent.com/42783698/225317061-9cd26ad7-fb02-4545-aae0-79eda384c08c.png)


Спасибо

2023-03-15 15:58 UTC, andryxxa93 requested changes
Здравствуйте!
Отличная работа 👍 
Что понравилось:
- Реализован механизм обновления токена
- Роутинг настроен и работает корректно
- Хороший `codestyle`

Что необходимо исправить:
- После успешного прохождения процедуры регистрации показывает сообщение об ошибке, хотя запрос не упал. 

<img width="1440" alt="Снимок экрана 2023-03-15 в 18 54 12" src="https://user-images.githubusercontent.com/60173362/225366998-5a21555f-dc17-4dc3-8591-94563d689534.png">

- Роуты `/login` `/register` `/forgot-password` не должны быть доступны авторизованному пользователю.
- Роут `/reset-password` должен быть доступен только через роут `/forgot-password`.
- Роут `/profile` не должен быть доступен для неавторизованного пользователя.
- По заданию необходимо, чтобы при нажатии на ингредиент открывалось модальное окно, а только при прямо переходе на ссылку с ингредиентом открывалась отдельная страница. У вас сейчас открывается отдельная страница в любой ситуации.
- Лого обычно делают ссылкой на главную страницу.
- Не стоит использовать `window.location.replace` - из-за него сбрасывается состояние хранилища. Специально для роутинга по SPA есть хук `useNavigate` - https://reactrouter.com/en/main/hooks/use-navigate.


В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-15 15:58 UTC, andryxxa93 commented on src/components/protected-route.jsx
> +export function ProtectedRoute({ children, isGuestOnly, ...rest }) {
**Можно лучше**
Вместо того, чтобы создавать два отдельных компонента для защита роутов от авторизованных и не авторизованных пользователей можно их логику объединить в одном. Ведь компоненты на самом деле практически идентичны, за исключением порядка операндов в тернарном операторе. 

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-03-15 15:58 UTC, andryxxa93 commented on src/pages/feed.jsx
> +        (itemsRequest || feedRequest) &&
**Можно лучше**
Очень длинные и многоаспектные условия, если что-то пойдёт не так дебажить такое будет очень трудно. Рекомендую их делать меньше.

2023-03-17 14:14 UTC, danielginz commented on src/app.jsx
> +    state => state.items
Я сделал вот так 
![image](https://user-images.githubusercontent.com/42783698/225928811-d49f95b9-8ced-4642-b68c-a8c99e9524e4.png)
![image](https://user-images.githubusercontent.com/42783698/225929561-be916396-8de4-4fcd-af63-b881aa4db563.png)

и почему-то валится. Оставил пока так:
![image](https://user-images.githubusercontent.com/42783698/225929777-0d10ea4e-1656-4f63-b1a0-99a75d9c0c4c.png)

2023-03-17 14:18 UTC, danielginz commented
Извините, можно вопрос. Я пишу в Вебшторме и у меня не получается отладидь дебаг. Может вы можете подсказать, как сконфигурировать дебаг, может где-то то почитать?

Жму сюда, ствалю брекпоинт но дебаг не включается
![image](https://user-images.githubusercontent.com/42783698/225930870-cfd88eee-d993-4a32-a97a-615bc6d9550b.png)


Спасибо

2023-03-17 14:32 UTC, danielginz commented on src/components/protected-route.jsx
> +export function ProtectedRoute({ children, isGuestOnly, ...rest }) {
Я сделал 2 компонента роута, пробовал объединить их в один, но решил, что проще, когда они 2 отдельных. Внутри они теперь проще, чем были.

Также у меня вылетает все время следующий warning:
VM19 react_devtools_backend.js:2655 Warning: Cannot update a component
![image](https://user-images.githubusercontent.com/42783698/225934283-6cdb516e-b25e-47f5-8863-69c8c0ff30ca.png)
Не успел ещё разобраться в нём.

2023-03-18 06:22 UTC, andryxxa93 commented
> Извините, можно вопрос. Я пишу в Вебшторме и у меня не получается отладидь дебаг. Может вы можете подсказать, как сконфигурировать дебаг, может где-то то почитать?
> 
> Жму сюда, ствалю брекпоинт но дебаг не включается ![image](https://user-images.githubusercontent.com/42783698/225930870-cfd88eee-d993-4a32-a97a-615bc6d9550b.png)
> 
> Спасибо

Сам пользую WS, но ещё ни разу не пользовался их debug. Когда это необходимо я использую консоль разработчика. 

Можете попробовать вот эту статью использовать - https://blog.jetbrains.com/webstorm/2017/01/debugging-react-apps/

2023-03-18 06:29 UTC, andryxxa93 commented
Супер! Отлично поработали, но осталось ещё пару замечаний:

- Роут `/reset-password` попрежнему доступен для авторизованного пользователя. Да и по прямой ссылке, в обход `/forgot-password` тоже доступен.
- При нажатии на ингредиент не меняется `url`

<img width="846" alt="Снимок экрана 2023-03-18 в 09 26 14" src="https://user-images.githubusercontent.com/60173362/226089315-4498429b-e08e-4e26-a695-ddf87b24b86a.png">

- В шапке панели навигации должны быть активна та ссылка на маршрут, где сейчас находится пользователь. Ссылка должна оставаться активной, если пользователь попадает на вложенные динамические маршруты. Например на "Историю заказов".

2023-03-18 19:31 UTC, danielginz commented
**Роут /reset-password попрежнему доступен для авторизованного пользователя. Да и по прямой ссылке, в обход /forgot-password тоже доступен.**
Я думаю, что я исправил следующим образом:
<Route path={RESET_PASSWORD} element={<ProtectedGuestRoute element={<ResetPasswordPage element={<ForgotPasswordPage />}/>}/>} />


**При нажатии на ингредиент не меняется url**
У меня не получается. Я добавил **window.location.assign(`/ingredients/${props.item._id}`);**  в компоненте burger-ingredients-card.jsx, но он сразу переводит на игридиент, как на отдельную страницу, а не как Modal компонент.

2023-03-19 06:41 UTC, andryxxa93 commented
- Вам нужно использовать средства роутинга для определения, показывать ли попап с деталями, или показывать страницу. Вам должны были дать ссылку на документацию по этой логике. Вот она https://reactrouter.com/web/example/modal-gallery . Пожалуйста, посоветуйтесь с наставником.
- Роут `reset-password` уже не доступен для авторизованных юзеров - это отлично, но по-прежнему доступен для неавторизованных по прямой ссылке. Чтобы этого избежать создайте в хранилище дополнительное поле - isResetPassword например, которое будете ставить в true если пользователь побывал на странице `forgot-password` и успешно отправил запрос на восстановления пароля.

2023-03-21 15:35 UTC, danielginz commented
Добрый вечер,
Спасибо за комментарии, это полезно, я узнал много навого )
Присылаю обновлённую версию

2023-03-22 08:12 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-24 07:39 UTC, merged