Sprint 5/step 1
danielginz/react-burger pull request #7
Opened 2023-05-18 14:12 UTC by danielginz

2023-05-18 14:34 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Сокеты открываются и закрываются согласно брифу
- Есть проверка ошибки токена в работе сокета
- Отличная работа с датами

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- При нажатии на заказ должна открываться модалка с заказом, а вот при переходе по прямой ссылке - отдельная страница, у вас сейчас всегда отдельная страница открывается.
- При открытии конкретного заказа на отдельной странице в нем содержится не вся информация об ингредиентах


https://github.com/danielginz/react-burger/assets/60173362/c251f82f-0805-473b-bf24-b448203ba193

- Столбцы "Готовы" и в "Работе" всё время пустые - пожалуйста обратите внимание на требования тех задания по поводу этих блоков.
- Если попытаться открыть прямой ссылкой страницу с заказом из "Истории заказов", то пользователь попадает просто на страницу профиля.
- Нужно рассматривать разный набор экшенов при работе с сокетом для авторизованного и неавторизованного пользователя, и задавать свой набор экшенов как аргумент при вызовах миддлвара wsMiddleware в configureStore.
- В строке `export const useAppSelector: TypedUseSelectorHook<any> = useSelector` вместо any необходимо использовать `RootState`

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-20 19:45 UTC, danielginz commented
Здравствуйте, я исправил ваши замечания.
По поводу экшенов в wsMiddleware - я сделал 2 экшена wsConnectionStartUsers и wsConnectionStartAll вместо одного wsConnectionStart, все остальные экшены одинаковые для авторизированных и не авторизированных пользователей(как я понимаю).
Спасибо

2023-05-21 09:38 UTC, andryxxa93 commented
**Необходимо исправить**
- У вас вместо номером заказов в строке "Готовы" показываются их айдишники.
- При открытии модального окна с заказом из "Истории заказов" - ингредиенты из карточек "залезают" на неё.

<img width="952" alt="Снимок экрана 2023-05-21 в 12 32 32" src="https://github.com/danielginz/react-burger/assets/60173362/fa0f4455-ac61-4d3d-adf1-fb8b4f5a430f">

2023-05-21 10:44 UTC, danielginz commented
**У вас вместо номером заказов в строке "Готовы" показываются их айдишники.**
Здравствуйте, это номер, просто я добавлял ему 2 нуля впереди и он стал. Я убрал это
Было так:
![image](https://github.com/danielginz/react-burger/assets/42783698/d16b6dd1-3ddf-422a-bee9-d4e98fa40010)

Теперь так:
![image](https://github.com/danielginz/react-burger/assets/42783698/3271733d-9078-47ac-b14b-538d381b8ecd)

2023-05-21 16:31 UTC, andryxxa93 commented
**Необходимо исправить**
- На странице "Лента заказов" в столбце "Готовы" и "В работе" показываются айдишники заказов, а не их номера.

<img width="1440" alt="Снимок экрана 2023-05-21 в 19 31 01" src="https://github.com/danielginz/react-burger/assets/60173362/42d2047a-322c-47da-aa55-9db361928e29">

2023-05-21 20:45 UTC, danielginz commented
Я исправил
![image](https://github.com/danielginz/react-burger/assets/42783698/509875e4-b136-43fe-b7a1-316f05557fbb)

2023-05-22 09:06 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-22 09:44 UTC, merged